import P2c from "./image/2c.png";
import P2d from "./image/2d.png";
import P2h from "./image/2h.png";
import P2s from "./image/2s.png";
import P3c from "./image/3c.png";
import P3d from "./image/3d.png";
import P3h from "./image/3h.png";
import P3s from "./image/3s.png";
import P4c from "./image/4c.png";
import P4d from "./image/4d.png";
import P4h from "./image/4h.png";
import P4s from "./image/4s.png";
import P5c from "./image/5c.png";
import P5d from "./image/5d.png";
import P5h from "./image/5h.png";
import P5s from "./image/5s.png";
import P6c from "./image/6c.png";
import P6d from "./image/6d.png";
import P6h from "./image/6h.png";
import P6s from "./image/6s.png";
import P7c from "./image/7c.png";
import P7d from "./image/7d.png";
import P7h from "./image/7h.png";
import P7s from "./image/7s.png";
import P8c from "./image/8c.png";
import P8d from "./image/8d.png";
import P8h from "./image/8h.png";
import P8s from "./image/8s.png";
import P9c from "./image/9c.png";
import P9d from "./image/9d.png";
import P9h from "./image/9h.png";
import P9s from "./image/9s.png";
import PTc from "./image/Tc.png";
import PTd from "./image/Td.png";
import PTh from "./image/Th.png";
import PTs from "./image/Ts.png";
import PJc from "./image/Jc.png";
import PJd from "./image/Jd.png";
import PJh from "./image/Jh.png";
import PJs from "./image/Js.png";
import PQc from "./image/Qc.png";
import PQd from "./image/Qd.png";
import PQh from "./image/Qh.png";
import PQs from "./image/Qs.png";
import PKc from "./image/Kc.png";
import PKd from "./image/Kd.png";
import PKh from "./image/Kh.png";
import PKs from "./image/Ks.png";
import PAc from "./image/Ac.png";
import PAd from "./image/Ad.png";
import PAh from "./image/Ah.png";
import PAs from "./image/As.png";


const pokerMap = new Map();
pokerMap.set("2c", P2c);
pokerMap.set("2d", P2d);
pokerMap.set("2h", P2h);
pokerMap.set("2s", P2s);
pokerMap.set("3c", P3c);
pokerMap.set("3d", P3d);
pokerMap.set("3h", P3h);
pokerMap.set("3s", P3s);
pokerMap.set("4c", P4c);
pokerMap.set("4d", P4d);
pokerMap.set("4h", P4h);
pokerMap.set("4s", P4s);
pokerMap.set("5c", P5c);
pokerMap.set("5d", P5d);
pokerMap.set("5h", P5h);
pokerMap.set("5s", P5s);
pokerMap.set("6c", P6c);
pokerMap.set("6d", P6d);
pokerMap.set("6h", P6h);
pokerMap.set("6s", P6s);
pokerMap.set("7c", P7c);
pokerMap.set("7d", P7d);
pokerMap.set("7h", P7h);
pokerMap.set("7s", P7s);
pokerMap.set("8c", P8c);
pokerMap.set("8d", P8d);
pokerMap.set("8h", P8h);
pokerMap.set("8s", P8s);
pokerMap.set("9c", P9c);
pokerMap.set("9d", P9d);
pokerMap.set("9h", P9h);
pokerMap.set("9s", P9s);
pokerMap.set("Tc", PTc);
pokerMap.set("Td", PTd);
pokerMap.set("Th", PTh);
pokerMap.set("Ts", PTs);
pokerMap.set("Jc", PJc);
pokerMap.set("Jd", PJd);
pokerMap.set("Jh", PJh);
pokerMap.set("Js", PJs);
pokerMap.set("Qc", PQc);
pokerMap.set("Qd", PQd);
pokerMap.set("Qh", PQh);
pokerMap.set("Qs", PQs);
pokerMap.set("Kc", PKc);
pokerMap.set("Kd", PKd);
pokerMap.set("Kh", PKh);
pokerMap.set("Ks", PKs);
pokerMap.set("Ac", PAc);
pokerMap.set("Ad", PAd);
pokerMap.set("Ah", PAh);
pokerMap.set("As", PAs);

export default function getImg(type) {
  return pokerMap.get(type)
}
